version: '3.8'

services:
  pii-shield-db:
    build: .
    container_name: mcp-pii-shield
    ports:
      - "3000:3000"
    environment:
      - TRANSPORT=sse
      - PORT=3000
      - PGHOST=100.92.174.76
      - PGPORT=5432
      - PGUSER=mps
      - PGPASSWORD=mps-db-super-secret-pass-2026-alpha
      - PGDATABASE=your_pgdb_name
      - MCP_API_KEY=${MCP_API_KEY}
      - ROSTER_PATH=./entityRoster.json
    restart: always
